import 'dotenv/config';
import path from 'node:path';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import { assetsRouter } from './routes/assets.routes.js';
import { assignmentsRouter } from './routes/assignments.routes.js';
import { dashboardRouter } from './routes/dashboard.routes.js';
import { reportsRouter } from './routes/reports.routes.js';
import { verificationRouter } from './routes/verification.routes.js';
import { bulkRouter } from './routes/bulk.routes.js';
import { locationsRouter } from './routes/locations.routes.js';
import { departmentAssetsRouter } from './routes/departmentAssets.routes.js';
import { errorHandler, notFound } from './middleware/errors.js';
import { flaskJsonResponse } from './utils/flask-json.js';

export const app = express();
app.use(helmet({ crossOriginResourcePolicy: { policy: 'cross-origin' } }));
app.use(cors({ origin: process.env.CLIENT_ORIGIN || 'http://localhost:5173' }));
app.use(express.json({ limit: '1mb' }));
app.use(flaskJsonResponse);
app.use('/uploads', express.static(path.resolve('uploads')));
app.use('/qrcodes', express.static(path.resolve('uploads', 'qrcodes')));
app.get('/api/health', (req, res) => res.json({ status: 'ok' }));
app.use('/api/assets', assetsRouter);
app.use('/api/assignments', assignmentsRouter);
app.use('/api/department-assets', departmentAssetsRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/api/reports', reportsRouter);
app.use('/api/verifications', verificationRouter);
app.use('/api/bulk', bulkRouter);
app.use('/api/locations', locationsRouter);
app.use(notFound);
app.use(errorHandler);
